### ISSUE TITLE
Add an example of excluding folders from yapf to the documentation

### ISSUE THREAD

**Issue by pksol** [AlexanderMelde/yapf-action#1]
I wanted to ignore my `tests` folder, so I had to hack a bit till I got to this way:

`args: --verbose --exclude '**/tests/**'` (the trivial way would be to send just `'tests/**'` as a parameter, but it assumes that the execution is inside the repository).

Can you include it to the documentation so people can use it quickly? I didn't do a pull request in case you wanted to solve it in a different way.

**Comment by AlexanderMelde** [comment]
Thank you for the idea and explanation, i will add it!

**Comment by AlexanderMelde** [comment]
Implemented in commit https://github.com/AlexanderMelde/yapf-action/commit/b65bdf018b459b4682de8ee990df623e65608abe .
