### ISSUE TITLE
Fix "yapf not found" in PR #3

### ISSUE THREAD

**Issue by AlexanderMelde** [AlexanderMelde/yapf-action#4]
see #3 for details, unfortunately i dont't have the time to investigate further into it currently, so @WildCard65 if you want to fix the bug, please send a new pull request if you have resolved the issue 👍

**Comment by AlexanderMelde** [comment]
@WildCard65 i have invited you to the test-repository i used, if you want you can play around there and maybe we can get it working. I also saved your changes in the [composite-action](https://github.com/AlexanderMelde/yapf-action/tree/composite-action) branch of this repo

**Comment by WildCard65** [comment]
I'll get to it when I get home.

**Comment by AlexanderMelde** [comment]
Due to inactivity, I'll close this now, if you are still interested, please create a new issue / re-open. 😄
